### ISSUE TITLE
remove dynamic import statements

### ISSUE THREAD

**Issue by raphaelschwinger** [simov/request-compose#7]
Thanks @simov for your great work again! This is the same as in your other [repo](https://github.com/simov/grant/issues/231) 

## Summary
Importing from paths generated at runtime breaks
parcel, see (parcel-bundler/parcel#4031),
or esbuild, see (evanw/esbuild#480).
This can lead to problems at runtime.

fixes #7

**Comment by simov** [comment]
Fixed in #8
